[FEAT] Update provider to use config
vapor/mongo-provider pull request #16
Opened 2017-05-21 05:06 UTC by plummer

Please let me know if this is incorrect, however I don't think this provider was correctly using the  values, it seemed to be using a separate url string.

2017-05-21 05:27 UTC, plummer commented
Added resolution for #8

2017-05-21 14:11 UTC, Joannis commented
I agree that MongoKitten configuration should be integrated with Vapor config files. But since MongoKitten already has a structure for [MongoDB configuration here](https://github.com/OpenKitten/MongoKitten/blob/mongokitten4/Sources/MongoKitten/Server/ClientSettings.swift).

I also think [SSL needs to be supported](https://github.com/OpenKitten/MongoKitten/blob/mongokitten4/Sources/MongoKitten/Server/SSLSettings.swift) in the configuration.

And production applications usually rely on ReplicaSets and/or sharded databases, which means [supporting multiple hosts](https://github.com/OpenKitten/MongoKitten/blob/mongokitten4/Sources/MongoKitten/Server/ClientSettings.swift#L129).

Regardless, you can always create a database using the whole MongoDB/MongoKitten URL featureset using the following:

```
let database = try Database("mongodb://localhost")
```

Which can become complex with multiple hosts, etc, too.

2017-05-21 21:28 UTC, Joannis requested changes

2017-05-21 21:28 UTC, Joannis commented on Sources/MongoProvider/Provider.swift
> +        func buildUrl(mongo: Config) throws -> String {
The config file could be mapped to [ClientSettings](https://github.com/OpenKitten/MongoKitten/blob/mongokitten4/Sources/MongoKitten/Server/ClientSettings.swift). That simplifies this function and improves compatibility with edge-case scenarios such as complex passwords with `%` and other URL reserved characters.

2017-05-21 21:28 UTC, Joannis commented on Sources/MongoProvider/Provider.swift
>          try self.init(url, maxConnectionsPerServer: maxConnectionsPerServer)
You could initialize a `Server` using the ClientSettings and subscript it using the `database` name to get a Database instance.

2017-05-25 03:49 UTC, plummer commented
Closing, a lot of edge cases here so i think it's easier to just use the full url.

2017-05-25 03:49 UTC, closed without merging